Repository catenax-ng/tx-digital-product-pass, pull requests merged in 2023-08, with the labels that each got.

#141 Bugfix/cmp 811/fix helm test: Fix workflow and test connection script
  .github/workflows/helm-test.yaml
  charts/digital-product-pass/templates/deployment-backend.yaml
  charts/digital-product-pass/templates/deployment-frontend.yaml
  charts/digital-product-pass/templates/pv-data.yaml
  charts/digital-product-pass/templates/pvc-data.yaml
  charts/digital-product-pass/templates/service-backend.yaml
  charts/digital-product-pass/templates/service-frontend.yaml
  charts/digital-product-pass/templates/tests/test-dpp-connection.yaml
  charts/digital-product-pass/values.yaml
Labels: helm-chart

#156 feature/cmp-680/administrator guide
  docs/admin guide/Admin_Guide.md
Labels: documentation

#155 feature/cmp-682/api documentation
  consumer-backend/productpass/docs/media/img2.png
  consumer-backend/productpass/readme.md
  deployment/helm/local/scripts/set_dev_values.sh
  deployment/helm/local/scripts/unset_dev_values.sh
  docs/GETTING-STARTED.md
  docs/SECRETS_MANAGEMENT.md
Labels: documentation

#154 feature/cmp-679/arc42 guide
  docs/arc42/Arc42.md
  docs/arc42/CancelFlow.jpeg
  docs/arc42/ContextDiagram.jpeg
  docs/arc42/CreateAPI.jpeg
  docs/arc42/CreateProcessFlow.jpeg
  docs/arc42/DeclineFlow.jpeg
  docs/arc42/GetStatus.jpeg
  docs/arc42/GraphicApplicationStateDiagram.jpg
  docs/arc42/GraphicBatteryPassportView.png
  docs/arc42/GraphicBatteryPassportViewGeneralInfo.png
  docs/arc42/GraphicSearchView.png
  docs/arc42/GraphicSystemScopeandContext.jpg
  docs/arc42/GraphicTechnicalIntegrationDesign.jpg
  docs/arc42/PassportRetrievalFlow.jpeg
  docs/arc42/SearchAPI.jpeg
  docs/arc42/SearchFlow.jpeg
  docs/arc42/SignAPI.jpeg
  docs/arc42/SignFlow.jpeg
  docs/arc42/StateDiagram.jpeg
  docs/arc42/TechnicalIntegrationResume.jpeg
Labels: documentation

#140 feature/cmp 655/decentral dtr: Decentral Digital Twin integration
  charts/digital-product-pass/values-beta.yaml
  charts/digital-product-pass/values-dev.yaml
  charts/digital-product-pass/values-int.yaml
  charts/digital-product-pass/values.yaml
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/config/DiscoveryConfig.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/config/DtrConfig.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/http/controllers/AppController.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/http/controllers/api/ContractController.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/listeners/AppListener.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/managers/DtrSearchManager.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/managers/ProcessManager.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/catenax/BpnDiscovery.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/catenax/Discovery.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/catenax/Dtr.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/catenax/EdcDiscoveryEndpoint.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/dtregistry/DigitalTwin3.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/dtregistry/EndPoint3.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/dtregistry/SubModel3.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/edc/AssetSearch.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/http/requests/DiscoverySearch.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/http/requests/Search.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/manager/SearchStatus.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/manager/Status.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/negotiation/Dataset.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/negotiation/Set.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/services/AasService.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/services/AuthenticationService.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/services/CatenaXService.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/services/DataPlaneService.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/services/DataTransferService.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/services/VaultService.java
  consumer-backend/productpass/src/main/java/utils/CatenaXUtil.java
  consumer-backend/productpass/src/main/java/utils/CrypUtil.java
  consumer-backend/productpass/src/main/java/utils/FileUtil.java
  consumer-backend/productpass/src/main/java/utils/HttpUtil.java
  consumer-backend/productpass/src/main/java/utils/JsonUtil.java
  consumer-backend/productpass/src/main/java/utils/ThreadUtil.java
  consumer-backend/productpass/src/main/resources/application.yml
Labels: backend
