Repository catenax-ng/tx-digital-product-pass, pull requests merged in 2023-12, with the labels that each got.

#196 Bugfix/cmp 978/qr code scanner
  src/assets/styles/components/general/footer.scss
  src/assets/styles/components/landing/searchView.scss
  src/components/general/QrcodeStrem.vue
  src/store/index.js
  src/views/SearchView.vue
Labels: frontend

#206 Feature/cmp 996/admin guide: Updated Admin Guide
  docs/admin guide/Admin_Guide.md
Labels: documentation

#204 Feature/cmp 954/physical dimensions aspect: Prepare and register physical dimensions aspect to the provider setup
  deployment/infrastructure/testing/testdata/testdata-payload.json
Labels: backend

#202 Feature/cmp 747/bpn block: Implemented Authorization mechanism in the Application
  charts/digital-product-pass/Chart.yaml
  charts/digital-product-pass/README.md
  charts/digital-product-pass/templates/configmap-backend.yaml
  charts/digital-product-pass/templates/deployment-backend.yaml
  charts/digital-product-pass/templates/deployment-frontend.yaml
  charts/digital-product-pass/templates/secret-backend.yaml
  charts/digital-product-pass/values-beta.yaml
  charts/digital-product-pass/values-dev.yaml
  charts/digital-product-pass/values-int.yaml
  charts/digital-product-pass/values.yaml
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/config/SecurityConfig.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/listeners/AppListener.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/models/auth/UserInfo.java
  consumer-backend/productpass/src/main/java/org/eclipse/tractusx/productpass/services/AuthenticationService.java
  consumer-backend/productpass/src/main/java/utils/JsonUtil.java
  consumer-backend/productpass/src/main/resources/application.yml
  entrypoint.sh
  src/App.vue
  src/components/general/ErrorComponent.vue
  src/components/general/Footer.vue
  src/components/general/NotAuthorizedComponent.vue
  src/components/general/NotAvailableComponent.vue
  src/main.js
  src/media/Home.png
  src/services/Authentication.js
  src/services/service.const.js
  src/utils/authUtil.js
  src/utils/cryptUtil.js
  src/utils/jsonUtil.js
Labels: backend
