Repository catenax-ng/tx-digital-product-pass, pull requests merged in 2024-01, with the labels that each got.

#207 Feature/cmp 804/create unit tests
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/http/controllers/api/ContractController.java
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/managers/ProcessManager.java
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/models/catenax/BpnDiscovery.java
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/models/manager/SearchStatus.java
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/services/AasService.java
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/services/DataTransferService.java
  dpp-backend/digitalproductpass/src/main/java/org/eclipse/tractusx/digitalproductpass/services/IrsService.java
  dpp-backend/digitalproductpass/src/main/java/utils/HttpUtil.java
  dpp-backend/digitalproductpass/src/main/java/utils/JsonUtil.java
  dpp-backend/digitalproductpass/src/test/java/managers/DtrSearchManagerTest.java
  dpp-backend/digitalproductpass/src/test/java/managers/ProcessDataModelTest.java
  dpp-backend/digitalproductpass/src/test/java/managers/ProcessManagerTest.java
  dpp-backend/digitalproductpass/src/test/java/managers/TreeManagerTest.java
  dpp-backend/digitalproductpass/src/test/java/mocks/MockedHttpSession.java
  dpp-backend/digitalproductpass/src/test/java/services/AasServiceTest.java
  dpp-backend/digitalproductpass/src/test/java/services/AuthenticationServiceTest.java
  dpp-backend/digitalproductpass/src/test/java/services/CatenaXServiceTest.java
  dpp-backend/digitalproductpass/src/test/java/services/DataPlaneServiceTest.java
  dpp-backend/digitalproductpass/src/test/java/services/DataTransferServiceTest.java
  dpp-backend/digitalproductpass/src/test/java/services/IrsServiceTest.java
  dpp-backend/digitalproductpass/src/test/java/utils/CrypUtilTest.java
  dpp-backend/digitalproductpass/src/test/java/utils/JsonUtilTest.java
  dpp-backend/digitalproductpass/src/test/java/utils/LogUtilTest.java
  dpp-backend/digitalproductpass/src/test/java/utils/SystemUtilTest.java
  dpp-backend/digitalproductpass/src/test/java/utils/YamlUtilTest.java
  dpp-backend/digitalproductpass/src/test/resources/application-test.yml
  dpp-backend/digitalproductpass/src/test/resources/dpp/assets/TestAsset.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/catalogs/TestContractOfferCatalog.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/catalogs/TestDigitalTwinCatalog.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/contractpolicies/TestPolicy.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/digitaltwins/TestDigitalTwin.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/discovery/MockedDiscoveryEndpoints.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/irs/TestJobHistory.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/irs/TestJobResponse.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/irs/TestStartJobResponse.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/irs/TestTreeDataModel.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/negotiation/TestResponseInitNegotiation.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/negotiation/TestResponseNegotiation.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/payloads/TestPassport.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/token/MockedToken.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/token/MockedUserInfo.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/transfer/TestResponseInitTransfer.json
  dpp-backend/digitalproductpass/src/test/resources/dpp/transfer/TestResponseTransfer.json
Labels: backend

#199 Feature/cmp 988/i18n and l10n service & structure
  src/assets/styles/components/general/header.scss
  src/components/general/Dialog.vue
  src/components/general/ErrorComponent.vue
  src/components/general/Footer.vue
  src/components/general/Header.vue
  src/components/general/LoadingComponent.vue
  src/components/general/RecursiveTree.vue
  src/components/general/SearchInput.vue
  src/components/general/TabsComponent.vue
  src/components/passport/BarChart.vue
  src/components/passport/BatteryCards.vue
  src/components/passport/Field.vue
  src/components/passport/GeneralCards.vue
  src/components/passport/PassportHeader.vue
  src/components/passport/Section.vue
  src/components/passport/sections/BatteryComposition.vue
  src/components/passport/sections/CellChemistry.vue
  src/components/passport/sections/Characteristics.vue
  src/components/passport/sections/Components.vue
  src/components/passport/sections/ElectrochemicalProperties.vue
  src/components/passport/sections/Exchange.vue
  src/components/passport/sections/GeneralInformation.vue
  src/components/passport/sections/Serialization.vue
  src/components/passport/sections/StateOfBattery.vue
  src/config/templates/descriptions.json
  src/config/templates/iconMappings.json
  src/main.js
  src/media/backgroundart.jpg
  src/translations/de.json
  src/translations/en.json
  src/views/HomeView.vue
  src/views/PassportView.vue
  src/views/SearchView.vue
Labels: frontend

#213 Bugfix/cmp-1014/general-cards-fix
  src/assets/MOCK/CX:XYZ78901:BAT-XYZ789.json
  src/assets/MOCK/IMR18650V1-depricated.json
  src/assets/MOCK/NCR186850B.json
  src/components/general/LoadingComponent.vue
  src/components/passport/Field.vue
  src/components/passport/GeneralCards.vue
  src/components/passport/sections/Characteristics.vue
  src/components/passport/sections/Identification.vue
  src/components/passport/sections/Sustainability.vue
  src/components/passport/sections/Typology.vue
  src/translations/de.json
  src/translations/en.json
Labels: frontend

#212 Bugfix/cmp-1008/qrcode-back-btn
  src/views/SearchView.vue
Labels: frontend

#224 Feature/cmp 1088/business statement: Updated business statement diagrams
  docs/business statement/Business Statement.md
  docs/business statement/GraphArchitectureFunctionalCut.png
  docs/business statement/GraphArchitectureFunctionalCut.svg
  docs/business statement/GraphBusinessProblem.png
  docs/business statement/GraphBusinessProblem.svg
Labels: documentation
